spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tutorial_spring
    username: postgres
    password: moi
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
  sql:
    init:
      mode: always

